// <auto-generated />
namespace UniversityManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class z5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(z5));
        
        string IMigrationMetadata.Id
        {
            get { return "201601201248469_z5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
